apiVersion: v1
kind: PersistentVolume
metadata:
  name: iscsi-pv
spec:
  capacity:
    storage: 1000Gi
  accessModes:
    - ReadWriteOnce
  iscsi:
     targetPortal: store1
     iqn: iqn.2016-02.local.store1
     lun: 0
     fsType: 'ext4'
     readOnly: false
